// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalBox.Infrastructure;

namespace sqlite.SignalBox.SubSignalBoxDbContext
{
    [DbContext(typeof(SignalBoxDbContext))]
    [Migration("20220203071951_develop_add_common_metrics")]
    partial class develop_add_common_metrics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("CustomerSegment", b =>
                {
                    b.Property<long>("InSegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SegmentsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InSegmentId", "SegmentsId");

                    b.HasIndex("SegmentsId");

                    b.ToTable("SegmentTrackedUser");
                });

            modelBuilder.Entity("ItemsRecommendationRecommendableItem", b =>
                {
                    b.Property<long>("ItemsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecommendationsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemsId", "RecommendationsId");

                    b.HasIndex("RecommendationsId");

                    b.ToTable("ItemsRecommendationRecommendableItem");
                });

            modelBuilder.Entity("ItemsRecommenderRecommendableItem", b =>
                {
                    b.Property<long>("ItemsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecommendersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemsId", "RecommendersId");

                    b.HasIndex("RecommendersId");

                    b.ToTable("ItemsRecommenderRecommendableItem");
                });

            modelBuilder.Entity("MetricRecommenderEntityBase", b =>
                {
                    b.Property<long>("LearningFeaturesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecommendersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LearningFeaturesId", "RecommendersId");

                    b.HasIndex("RecommendersId");

                    b.ToTable("FeatureRecommenderEntityBase");
                });

            modelBuilder.Entity("ParameterParameterSetRecommender", b =>
                {
                    b.Property<long>("ParameterSetRecommendersId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ParametersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParameterSetRecommendersId", "ParametersId");

                    b.HasIndex("ParametersId");

                    b.ToTable("ParameterParameterSetRecommender");
                });

            modelBuilder.Entity("SignalBox.Core.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CommonUserId");

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommonId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("CommonId", "EnvironmentId")
                        .IsUnique();

                    b.ToTable("TrackedUsers");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            CommonId = "anonymous",
                            Created = 0L,
                            LastUpdated = 0L,
                            Name = "Anonymous Customer",
                            Properties = "{}"
                        });
                });

            modelBuilder.Entity("SignalBox.Core.CustomerEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CommonUserId");

                    b.Property<long?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventKind")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RecommendationCorrelatorId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TrackedUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("RecommendationCorrelatorId");

                    b.HasIndex("SourceId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TrackedUserId");

                    b.HasIndex("EventId", "EnvironmentId")
                        .IsUnique();

                    b.ToTable("TrackedUserEvents");
                });

            modelBuilder.Entity("SignalBox.Core.Environment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("SignalBox.Core.HashedApiKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlgorithmName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApiKeyType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("HashedKey")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastExchanged")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalExchanges")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("SignalBox.Core.HistoricCustomerMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("MetricId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("REAL");

                    b.Property<string>("StringValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("TrackedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackedUserId");

                    b.HasIndex("MetricId", "TrackedUserId", "Version")
                        .IsUnique();

                    b.ToTable("HistoricTrackedUserFeatures");
                });

            modelBuilder.Entity("SignalBox.Core.IntegratedSystem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cache")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CacheLastRefreshed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("IntegratedSystem");

                    b.Property<long?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntegrationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("('NotConfigured')");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenResponse")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TokenResponseUpdated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("IntegratedSystems");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IntegratedSystem");
                });

            modelBuilder.Entity("SignalBox.Core.LatestMetricVersion", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HistoricCustomerMetricId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MetricId")
                        .HasColumnType("INTEGER");

                    b.ToView("View_MaxHistoricCustomerMetricVersion");
                });

            modelBuilder.Entity("SignalBox.Core.Metric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommonId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("CommonId", "EnvironmentId")
                        .IsUnique();

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 100L,
                            CommonId = "revenue",
                            Created = 0L,
                            LastUpdated = 0L,
                            Name = "Revenue",
                            Properties = "{}"
                        },
                        new
                        {
                            Id = 101L,
                            CommonId = "total_events",
                            Created = 0L,
                            LastUpdated = 0L,
                            Name = "Total Events",
                            Properties = "{}"
                        });
                });

            modelBuilder.Entity("SignalBox.Core.MetricGenerator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FilterSelectAggregateSteps")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratorType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastEnqueued")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("MetricId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetricId");

                    b.ToTable("FeatureGenerators");

                    b.HasData(
                        new
                        {
                            Id = 100L,
                            Created = 0L,
                            FilterSelectAggregateSteps = "[{\"Order\":1,\"Filter\":null,\"Select\":{\"PropertyNameMatch\":null},\"Aggregate\":null},{\"Order\":2,\"Filter\":null,\"Select\":null,\"Aggregate\":{\"AggregationType\":0}}]",
                            GeneratorType = "FilterSelectAggregate",
                            LastUpdated = 0L,
                            MetricId = 101L
                        });
                });

            modelBuilder.Entity("SignalBox.Core.Metrics.Destinations.MetricDestinationBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConnectedSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MetricId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedSystemId");

                    b.HasIndex("MetricId");

                    b.ToTable("FeatureDestinations");

                    b.HasDiscriminator<string>("Discriminator").HasValue("MetricDestinationBase");
                });

            modelBuilder.Entity("SignalBox.Core.ModelRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("HostingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoringUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Swagger")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelRegistrations");
                });

            modelBuilder.Entity("SignalBox.Core.Parameter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommonId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("CommonId", "EnvironmentId")
                        .IsUnique();

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("SignalBox.Core.RecommendableItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DirectCost")
                        .HasColumnType("REAL");

                    b.Property<string>("Discriminator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Product");

                    b.Property<long?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("ListPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommonId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("CommonId", "EnvironmentId")
                        .IsUnique();

                    b.ToTable("RecommendableItems");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            CommonId = "default",
                            Created = 0L,
                            Description = "The default recommendable item. When this item is recommended, no action should be taken.",
                            Discriminator = "RecommendableItem",
                            LastUpdated = 0L,
                            Name = "Default Item",
                            Properties = "{}"
                        });
                });

            modelBuilder.Entity("SignalBox.Core.Recommendations.Destinations.RecommendationDestinationBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ConnectedSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("RecommenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedSystemId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("RecommenderId");

                    b.ToTable("RecommendationDestinations");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RecommendationDestinationBase");
                });

            modelBuilder.Entity("SignalBox.Core.Recommendations.ItemsRecommendation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModelInput")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelInputType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelOutput")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelOutputType")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RecommendationCorrelatorId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RecommenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommenderType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scores")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TargetMetricId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TrackedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("RecommendationCorrelatorId");

                    b.HasIndex("RecommenderId");

                    b.HasIndex("TargetMetricId");

                    b.HasIndex("TrackedUserId");

                    b.ToTable("ItemsRecommendations");
                });

            modelBuilder.Entity("SignalBox.Core.Recommendations.ParameterSetRecommendation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModelInput")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelInputType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelOutput")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelOutputType")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RecommendationCorrelatorId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RecommenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommenderType")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TargetMetricId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TrackedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("RecommendationCorrelatorId");

                    b.HasIndex("RecommenderId");

                    b.HasIndex("TargetMetricId");

                    b.HasIndex("TrackedUserId");

                    b.ToTable("ParameterSetRecommendations");
                });

            modelBuilder.Entity("SignalBox.Core.Recommendations.RecommendationCorrelator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("ModelRegistrationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ModelRegistrationId1")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RecommenderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelRegistrationId");

                    b.HasIndex("ModelRegistrationId1");

                    b.HasIndex("RecommenderId");

                    b.ToTable("RecommendationCorrelators");
                });

            modelBuilder.Entity("SignalBox.Core.Recommenders.InvokationLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CorrelatorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("InvokeEnded")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InvokeStarted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Messages")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelResponse")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RecommenderEntityBaseId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecommenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommenderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TrackedUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CorrelatorId");

                    b.HasIndex("InvokeStarted");

                    b.HasIndex("RecommenderEntityBaseId");

                    b.HasIndex("TrackedUserId");

                    b.ToTable("InvokationLogEntry");
                });

            modelBuilder.Entity("SignalBox.Core.Recommenders.RecommenderEntityBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorHandling")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("ModelRegistrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.Property<string>("Settings")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerCollection")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommonId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ModelRegistrationId");

                    b.HasIndex("CommonId", "EnvironmentId")
                        .IsUnique();

                    b.ToTable("Recommenders");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RecommenderEntityBase");
                });

            modelBuilder.Entity("SignalBox.Core.Recommenders.RecommenderTargetVariableValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("End")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("RecommenderId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Start")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecommenderId", "Name", "Version")
                        .IsUnique();

                    b.ToTable("RecommenderTargetVariableValue");
                });

            modelBuilder.Entity("SignalBox.Core.RewardSelector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SelectorType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionName", "SelectorType")
                        .IsUnique();

                    b.ToTable("RewardSelectors");
                });

            modelBuilder.Entity("SignalBox.Core.Segment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("SignalBox.Core.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseName")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenant", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("SignalBox.Core.TenantMembership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique();

                    b.ToTable("TenantMembership", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("SignalBox.Core.TenantTermsOfServiceAcceptance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcceptedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Version", "AcceptedByUserId")
                        .IsUnique();

                    b.ToTable("TenantTermsOfServiceAcceptance", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("SignalBox.Core.Touchpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommonId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("CommonId", "EnvironmentId")
                        .IsUnique();

                    b.ToTable("Touchpoints");
                });

            modelBuilder.Entity("SignalBox.Core.TrackedUserAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionValue")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AssociatedRevenue")
                        .HasColumnType("REAL");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CommonUserId");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FeedbackScore")
                        .HasColumnType("REAL");

                    b.Property<long?>("IntegratedSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("RecommendationCorrelatorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TrackedUserEventId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TrackedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionName");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RecommendationCorrelatorId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TrackedUserEventId");

                    b.HasIndex("TrackedUserId");

                    b.ToTable("TrackedUserActions");
                });

            modelBuilder.Entity("SignalBox.Core.TrackedUserSystemMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("IntegratedSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("TrackedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntegratedSystemId");

                    b.HasIndex("TrackedUserId");

                    b.HasIndex("UserId", "TrackedUserId", "IntegratedSystemId")
                        .IsUnique();

                    b.ToTable("TrackUserSystemMaps");
                });

            modelBuilder.Entity("SignalBox.Core.TrackedUserTouchpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("TouchpointId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrackedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Values")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TouchpointId");

                    b.HasIndex("TrackedUserId");

                    b.ToTable("TrackedUserTouchpoints");
                });

            modelBuilder.Entity("SignalBox.Core.WebhookReceiver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EndpointId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IntegratedSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SharedSecret")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId")
                        .IsUnique();

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("IntegratedSystemId");

                    b.ToTable("WebhookReceivers");
                });

            modelBuilder.Entity("SignalBox.Core.Integrations.Custom.CustomIntegratedSystem", b =>
                {
                    b.HasBaseType("SignalBox.Core.IntegratedSystem");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationSecret")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("CustomIntegratedSystem");
                });

            modelBuilder.Entity("SignalBox.Core.Metrics.Destinations.HubspotContactPropertyMetricDestination", b =>
                {
                    b.HasBaseType("SignalBox.Core.Metrics.Destinations.MetricDestinationBase");

                    b.Property<string>("HubspotPropertyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("HubspotContactPropertyMetricDestination");
                });

            modelBuilder.Entity("SignalBox.Core.Metrics.Destinations.WebhookMetricDestination", b =>
                {
                    b.HasBaseType("SignalBox.Core.Metrics.Destinations.MetricDestinationBase");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("WebhookMetricDestination");
                });

            modelBuilder.Entity("SignalBox.Core.Recommendations.Destinations.SegmentSourceFunctionDestination", b =>
                {
                    b.HasBaseType("SignalBox.Core.Recommendations.Destinations.RecommendationDestinationBase");

                    b.Property<string>("Endpoint")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SegmentSourceFunctionDestination");
                });

            modelBuilder.Entity("SignalBox.Core.Recommendations.Destinations.WebhookDestination", b =>
                {
                    b.HasBaseType("SignalBox.Core.Recommendations.Destinations.RecommendationDestinationBase");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("WebhookDestination_Endpoint");

                    b.HasDiscriminator().HasValue("WebhookDestination");
                });

            modelBuilder.Entity("SignalBox.Core.Recommenders.ItemsRecommender", b =>
                {
                    b.HasBaseType("SignalBox.Core.Recommenders.RecommenderEntityBase");

                    b.Property<long?>("BaselineItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfItemsToRecommend")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TargetMetricId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("BaselineItemId");

                    b.HasIndex("TargetMetricId");

                    b.HasDiscriminator().HasValue("ItemsRecommender");
                });

            modelBuilder.Entity("SignalBox.Core.Recommenders.ParameterSetRecommender", b =>
                {
                    b.HasBaseType("SignalBox.Core.Recommenders.RecommenderEntityBase");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterBounds")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoringUrl")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("ParameterSetRecommender");
                });

            modelBuilder.Entity("CustomerSegment", b =>
                {
                    b.HasOne("SignalBox.Core.Customer", null)
                        .WithMany()
                        .HasForeignKey("InSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalBox.Core.Segment", null)
                        .WithMany()
                        .HasForeignKey("SegmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemsRecommendationRecommendableItem", b =>
                {
                    b.HasOne("SignalBox.Core.RecommendableItem", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalBox.Core.Recommendations.ItemsRecommendation", null)
                        .WithMany()
                        .HasForeignKey("RecommendationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemsRecommenderRecommendableItem", b =>
                {
                    b.HasOne("SignalBox.Core.RecommendableItem", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalBox.Core.Recommenders.ItemsRecommender", null)
                        .WithMany()
                        .HasForeignKey("RecommendersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MetricRecommenderEntityBase", b =>
                {
                    b.HasOne("SignalBox.Core.Metric", null)
                        .WithMany()
                        .HasForeignKey("LearningFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalBox.Core.Recommenders.RecommenderEntityBase", null)
                        .WithMany()
                        .HasForeignKey("RecommendersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParameterParameterSetRecommender", b =>
                {
                    b.HasOne("SignalBox.Core.Recommenders.ParameterSetRecommender", null)
                        .WithMany()
                        .HasForeignKey("ParameterSetRecommendersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalBox.Core.Parameter", null)
                        .WithMany()
                        .HasForeignKey("ParametersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SignalBox.Core.Customer", b =>
                {
                    b.HasOne("SignalBox.Core.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("SignalBox.Core.CustomerEvent", b =>
                {
                    b.HasOne("SignalBox.Core.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SignalBox.Core.Recommendations.RecommendationCorrelator", "RecommendationCorrelator")
                        .WithMany()
                        .HasForeignKey("RecommendationCorrelatorId");

                    b.HasOne("SignalBox.Core.IntegratedSystem", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.HasOne("SignalBox.Core.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("TrackedUserId");

                    b.Navigation("Customer");

                    b.Navigation("Environment");

                    b.Navigation("RecommendationCorrelator");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SignalBox.Core.HistoricCustomerMetric", b =>
                {
                    b.HasOne("SignalBox.Core.Metric", "Metric")
                        .WithMany("HistoricTrackedUserFeatures")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalBox.Core.Customer", "Customer")
                        .WithMany("HistoricCustomerMetrics")
                        .HasForeignKey("TrackedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("SignalBox.Core.IntegratedSystem", b =>
                {
                    b.HasOne("SignalBox.Core.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId");

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("SignalBox.Core.Metric", b =>
                {
                    b.HasOne("SignalBox.Core.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("SignalBox.Core.MetricGenerator", b =>
                {
                    b.HasOne("SignalBox.Core.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("SignalBox.Core.Metrics.Destinations.MetricDestinationBase", b =>
                {
                    b.HasOne("SignalBox.Core.IntegratedSystem", "ConnectedSystem")
                        .WithMany()
                        .HasForeignKey("ConnectedSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalBox.Core.Metric", "Metric")
                        .WithMany("Destinations")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectedSystem");

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("SignalBox.Core.Parameter", b =>
                {
                    b.HasOne("SignalBox.Core.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("SignalBox.Core.RecommendableItem", b =>
                {
                    b.HasOne("SignalBox.Core.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("SignalBox.Core.Recommendations.Destinations.RecommendationDestinationBase", b =>
                {
                    b.HasOne("SignalBox.Core.IntegratedSystem", "ConnectedSystem")
                        .WithMany()
                        .HasForeignKey("ConnectedSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalBox.Core.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId");

                    b.HasOne("SignalBox.Core.Recommenders.RecommenderEntityBase", "Recommender")
                        .WithMany("RecommendationDestinations")
                        .HasForeignKey("RecommenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectedSystem");

                    b.Navigation("Environment");

                    b.Navigation("Recommender");
                });

            modelBuilder.Entity("SignalBox.Core.Recommendations.ItemsRecommendation", b =>
                {
                    b.HasOne("SignalBox.Core.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SignalBox.Core.Recommendations.RecommendationCorrelator", "RecommendationCorrelator")
                        .WithMany()
                        .HasForeignKey("RecommendationCorrelatorId");

                    b.HasOne("SignalBox.Core.Recommenders.ItemsRecommender", "Recommender")
                        .WithMany("Recommendations")
                        .HasForeignKey("RecommenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SignalBox.Core.Metric", "TargetMetric")
                        .WithMany()
                        .HasForeignKey("TargetMetricId");

                    b.HasOne("SignalBox.Core.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("TrackedUserId");

                    b.Navigation("Customer");

                    b.Navigation("Environment");

                    b.Navigation("RecommendationCorrelator");

                    b.Navigation("Recommender");

                    b.Navigation("TargetMetric");
                });

            modelBuilder.Entity("SignalBox.Core.Recommendations.ParameterSetRecommendation", b =>
                {
                    b.HasOne("SignalBox.Core.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SignalBox.Core.Recommendations.RecommendationCorrelator", "RecommendationCorrelator")
                        .WithMany()
                        .HasForeignKey("RecommendationCorrelatorId");

                    b.HasOne("SignalBox.Core.Recommenders.ParameterSetRecommender", "Recommender")
                        .WithMany("Recommendations")
                        .HasForeignKey("RecommenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SignalBox.Core.Metric", "TargetMetric")
                        .WithMany()
                        .HasForeignKey("TargetMetricId");

                    b.HasOne("SignalBox.Core.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("TrackedUserId");

                    b.Navigation("Customer");

                    b.Navigation("Environment");

                    b.Navigation("RecommendationCorrelator");

                    b.Navigation("Recommender");

                    b.Navigation("TargetMetric");
                });

            modelBuilder.Entity("SignalBox.Core.Recommendations.RecommendationCorrelator", b =>
                {
                    b.HasOne("SignalBox.Core.ModelRegistration", "ModelRegistration")
                        .WithMany()
                        .HasForeignKey("ModelRegistrationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SignalBox.Core.ModelRegistration", null)
                        .WithMany("Correlators")
                        .HasForeignKey("ModelRegistrationId1");

                    b.HasOne("SignalBox.Core.Recommenders.RecommenderEntityBase", "Recommender")
                        .WithMany("RecommendationCorrelators")
                        .HasForeignKey("RecommenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModelRegistration");

                    b.Navigation("Recommender");
                });

            modelBuilder.Entity("SignalBox.Core.Recommenders.InvokationLogEntry", b =>
                {
                    b.HasOne("SignalBox.Core.Recommendations.RecommendationCorrelator", "Correlator")
                        .WithMany()
                        .HasForeignKey("CorrelatorId");

                    b.HasOne("SignalBox.Core.Recommenders.RecommenderEntityBase", null)
                        .WithMany("RecommenderInvokationLogs")
                        .HasForeignKey("RecommenderEntityBaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SignalBox.Core.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("TrackedUserId");

                    b.Navigation("Correlator");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SignalBox.Core.Recommenders.RecommenderEntityBase", b =>
                {
                    b.HasOne("SignalBox.Core.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SignalBox.Core.ModelRegistration", "ModelRegistration")
                        .WithMany("Recommenders")
                        .HasForeignKey("ModelRegistrationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Environment");

                    b.Navigation("ModelRegistration");
                });

            modelBuilder.Entity("SignalBox.Core.Segment", b =>
                {
                    b.HasOne("SignalBox.Core.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId");

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("SignalBox.Core.TenantMembership", b =>
                {
                    b.HasOne("SignalBox.Core.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SignalBox.Core.TenantTermsOfServiceAcceptance", b =>
                {
                    b.HasOne("SignalBox.Core.Tenant", "Tenant")
                        .WithMany("AcceptedTerms")
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SignalBox.Core.Touchpoint", b =>
                {
                    b.HasOne("SignalBox.Core.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("SignalBox.Core.TrackedUserAction", b =>
                {
                    b.HasOne("SignalBox.Core.Recommendations.RecommendationCorrelator", "RecommendationCorrelator")
                        .WithMany()
                        .HasForeignKey("RecommendationCorrelatorId");

                    b.HasOne("SignalBox.Core.CustomerEvent", "TrackedUserEvent")
                        .WithMany("Actions")
                        .HasForeignKey("TrackedUserEventId");

                    b.HasOne("SignalBox.Core.Customer", "Customer")
                        .WithMany("Actions")
                        .HasForeignKey("TrackedUserId");

                    b.Navigation("Customer");

                    b.Navigation("RecommendationCorrelator");

                    b.Navigation("TrackedUserEvent");
                });

            modelBuilder.Entity("SignalBox.Core.TrackedUserSystemMap", b =>
                {
                    b.HasOne("SignalBox.Core.IntegratedSystem", "IntegratedSystem")
                        .WithMany()
                        .HasForeignKey("IntegratedSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalBox.Core.Customer", "Customer")
                        .WithMany("IntegratedSystemMaps")
                        .HasForeignKey("TrackedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("IntegratedSystem");
                });

            modelBuilder.Entity("SignalBox.Core.TrackedUserTouchpoint", b =>
                {
                    b.HasOne("SignalBox.Core.Touchpoint", "Touchpoint")
                        .WithMany("TrackedUserTouchpoints")
                        .HasForeignKey("TouchpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalBox.Core.Customer", "Customer")
                        .WithMany("TrackedUserTouchpoints")
                        .HasForeignKey("TrackedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Touchpoint");
                });

            modelBuilder.Entity("SignalBox.Core.WebhookReceiver", b =>
                {
                    b.HasOne("SignalBox.Core.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SignalBox.Core.IntegratedSystem", "IntegratedSystem")
                        .WithMany("WebhookReceivers")
                        .HasForeignKey("IntegratedSystemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Environment");

                    b.Navigation("IntegratedSystem");
                });

            modelBuilder.Entity("SignalBox.Core.Recommenders.ItemsRecommender", b =>
                {
                    b.HasOne("SignalBox.Core.RecommendableItem", "BaselineItem")
                        .WithMany()
                        .HasForeignKey("BaselineItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SignalBox.Core.Metric", "TargetMetric")
                        .WithMany()
                        .HasForeignKey("TargetMetricId");

                    b.Navigation("BaselineItem");

                    b.Navigation("TargetMetric");
                });

            modelBuilder.Entity("SignalBox.Core.Customer", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("HistoricCustomerMetrics");

                    b.Navigation("IntegratedSystemMaps");

                    b.Navigation("TrackedUserTouchpoints");
                });

            modelBuilder.Entity("SignalBox.Core.CustomerEvent", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("SignalBox.Core.IntegratedSystem", b =>
                {
                    b.Navigation("WebhookReceivers");
                });

            modelBuilder.Entity("SignalBox.Core.Metric", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("HistoricTrackedUserFeatures");
                });

            modelBuilder.Entity("SignalBox.Core.ModelRegistration", b =>
                {
                    b.Navigation("Correlators");

                    b.Navigation("Recommenders");
                });

            modelBuilder.Entity("SignalBox.Core.Recommenders.RecommenderEntityBase", b =>
                {
                    b.Navigation("RecommendationCorrelators");

                    b.Navigation("RecommendationDestinations");

                    b.Navigation("RecommenderInvokationLogs");
                });

            modelBuilder.Entity("SignalBox.Core.Tenant", b =>
                {
                    b.Navigation("AcceptedTerms");
                });

            modelBuilder.Entity("SignalBox.Core.Touchpoint", b =>
                {
                    b.Navigation("TrackedUserTouchpoints");
                });

            modelBuilder.Entity("SignalBox.Core.Recommenders.ItemsRecommender", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("SignalBox.Core.Recommenders.ParameterSetRecommender", b =>
                {
                    b.Navigation("Recommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
