# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Web Channel Script CI CD

trigger:
  - main

pool:
  vmImage: ubuntu-latest
variables:
  - group: Azure_Dev
steps:
  - script: az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
    displayName: "az login"

  - script: ./upload-to-blob.sh
    displayName: "Upload to blob"
    workingDirectory: clients/scripts/webChannel
