// TODO: Refactor all links to use routes so that there will be only 1 source of truth

export const routes = {
  admin: "admin",
  profile: "profile",
  trackedUsers: "tracked-users",
  customers: "customers",
  metrics: "metrics",
  segments: "segments",
  parameters: "parameters",
  recommenders: "recommenders",
  promotions: "promotions",
  models: "models",
  events: "events",
  settings: "settings",
  tenantSettings: "tenant-settings",
  dataview: "dataview",
  reports: "reports",
  businesses: "businesses",
  channels: "channels",
  gettingStarted: "getting-started",
  docsApi: "docs/api",
  integrations: "integrations",
  activityFeed: "activity-feed",
};
