# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Dotnet Solution Build

trigger:
  - main
  - develop/*

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: "Use .NET 6 sdk"
    inputs:
      version: 6.0.x

  - script: dotnet build
    displayName: Dotnet build solution
    workingDirectory: app

  - script: dotnet publish
    displayName: Dotnet publish web
    workingDirectory: app/web
