# Cherry Docs Pipeline

trigger:
  batch: true
  branches:
    include:
      - main
      - develop/*
      - docs/*
  paths:
    include:
      - docs/*

pool:
      vmImage: ubuntu-latest

jobs:
  - job: build_docs
    displayName: Build Docs
    continueOnError: false
    steps:
      - script: npm i
        workingDirectory: docs/docusaurus
        displayName: "npm Install"

      - script: npm run build
        workingDirectory: docs/docusaurus
        displayName: "npm Builds"

      - task: PublishPipelineArtifact@1
        displayName: Publish docs Artifacts
        inputs:
          targetPath: $(System.DefaultWorkingDirectory)/docs/docusaurus/build
          artifactName: "docs"

  - job: deploy_dev
    displayName: Deploy devdocs
    variables:
      - group: Azure_Docs_Dev
    continueOnError: false
    dependsOn: build_docs
    condition: |
      and(succeeded(), or(
      startsWith(variables['Build.SourceBranch'], 'refs/heads/develop/'), 
      startsWith(variables['Build.SourceBranch'], 'refs/heads/docs/')))
    steps:
      - task: Pulumi@1
        displayName: Pulumi Preview
        inputs:
          command: "preview"
          stack: $(DEV_PULUMI_STACK)
          cwd: $(WORKING_DIRECTORY_PULUMI)
          createStack: true

      - task: DownloadPipelineArtifact@2
        displayName: Download Published Build Artifacts
        inputs:
          artifact: "docs"
          path: $(System.DefaultWorkingDirectory)/docs/docusaurus/build/

      - script: |
          sh ./devops-deploy.sh
        workingDirectory: docs/scripts
        displayName: Deploy docs to Azure dev

  - job: deploy_prod
    displayName: Deploy prod docs
    variables:
      - group: Azure_Docs_Prod
    continueOnError: false
    dependsOn: build_docs
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
      - task: Pulumi@1
        displayName: Pulumi Preview
        inputs:
          command: "preview"
          stack: $(PROD_PULUMI_STACK)
          cwd: $(WORKING_DIRECTORY_PULUMI)
          createStack: true

      - task: DownloadPipelineArtifact@2
        displayName: Download Published Build Artifacts
        inputs:
          artifact: "docs"
          path: $(System.DefaultWorkingDirectory)/docs/docusaurus/build/

      - script: |
          sh ./devops-deploy.sh
        workingDirectory: docs/scripts
        displayName: Deploy docs to Azure Prod
