# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true # batch changes if true; start a new build for every push if false (default)
  branches:
    include:
      - main
      - develop/*
    # exclude: [string]
  # tags:
  #   include: [string] # tag names which will trigger a build
  #   exclude: [string] # tag names which will not
  paths:
    include:
      - docs/* # file paths which must match to trigger a build
    # exclude: [] # file paths which will not trigger a build

pool:
  vmImage: ubuntu-latest

steps:
  - script: npm i
    workingDirectory: docs/docusaurus
    displayName: "NPM Install"

  - script: npm run build
    workingDirectory: docs/docusaurus
    displayName: "NPM Build"
